analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5681003
  lightness: 0.2389912
  brandStrength: 0.973867247113958
  brandColors:
    - '#FFFFFF'
    - '#252021'
    - '#C7C5C5'
    - '#E12028'
    - '#787677'
  rhythmicContrast: 0.4048909
typography_spectrum: 0.9205496
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0
favicon: null
name: SocialOutlier
